server {
	listen localhost:8003;

	allowed_methods GET POST;
	root /home/;
	error_page 403 /webServer/error_pages/Forbidden.html;
	autoindex on;

	location /webserver/
	{
		allowed_methods GET POST;
	}

	location /Desktop/
	{
		allowed_methods GET POST ;
	}
}
