server {
    listen 0.0.0.0:8004;
    root /webserv;
    allowed_methods GET POST DELETE;
    client_max_body_size 100000000;
	client_timeout 2;

    location / {
        root ./;
        allowed_methods GET POST DELETE;
        upload_store ./uploads;
        index www/html/index.html;
	    autoindex on;
    }

    location /uploads {
        root ./;
        allowed_methods GET POST DELETE;
        autoindex on;
    }

    location /gallery {
        root ./www/;
        index index.html;
        allowed_methods GET POST DELETE;
    }

    location /cgi-bin {
        root ./www/;
        allowed_methods GET POST;
        autoindex on;
        cgi_info .py /usr/bin/python3;
        cgi_info .sh /usr/bin/bash;
        cgi_info .js /usr/bin/node;
        cgi_info .php /usr/bin/php;

        cgi_info .c "gcc -o {OUTPUT} {INPUT} && {OUTPUT}";
        cgi_info .cpp "g++ -o {OUTPUT} {INPUT} && {OUTPUT}";
        cgi_info .java "javac {INPUT} && java {INPUT}";
    }
}
