server {
    listen 164.92.133.254:8005;
    listen 164.92.133.254:8007;
    root /webserv;
    allowed_methods GET POST;
    client_max_body_size 10000000;
	autoindex on;

    location / {
        root ./;
        allowed_methods GET POST DELETE;
        autoindex on;
    }
}

